require 'solidus_backend'
require 'solidus_core'
require 'solidus_support'
require 'solidus_sale_pricing/engine'
require 'solidus_sale_pricing/version'
require 'coffee_script'
require 'sass/rails'
require 'deface'